=== maximka76667/xml-facturas/facturas.dtd
<!-- Elementos reusables -->
<!ELEMENT nombre (#PCDATA) >
<!ELEMENT descripcion (#PCDATA) >
<!ELEMENT precio (#PCDATA) >
<!ELEMENT iva (#PCDATA) >

<!-- Facturas -->
<!ELEMENT facturas (provincias, poblaciones, clientes, productos, factura+)>

<!-- Provincias -->
<!ELEMENT provincias (provincia+) >

<!-- Provincia -->
<!ELEMENT provincia (nombre) >
<!ATTLIST provincia id CDATA #REQUIRED>

<!-- Poblaciones -->
<!ELEMENT poblaciones (poblacion+) >

<!-- Poblacion -->
<!ELEMENT poblacion (nombre) >
<!ATTLIST poblacion id_poblacion CDATA #REQUIRED 
    id_provincia CDATA #REQUIRED >

<!-- Clientes -->
<!ELEMENT clientes (cliente+) >

<!-- Cliente -->
<!ELEMENT cliente (nombre, apellidos, direccion*)>
<!ATTLIST cliente dni CDATA #REQUIRED >
<!ELEMENT apellidos (#PCDATA) >
<!ELEMENT direccion (codigo_poblacion, calle, numero, cp) >

<!-- Direccion -->
<!ELEMENT codigo_poblacion (#PCDATA) >
<!ELEMENT calle (#PCDATA) >
<!ELEMENT numero (#PCDATA) >
<!ELEMENT cp (#PCDATA) >

<!-- Productos -->
<!ELEMENT productos (producto+) >

<!-- Producto -->
<!ELEMENT producto (descripcion, precio, iva, stock) >
<!ATTLIST producto id CDATA #REQUIRED >
<!ELEMENT stock (#PCDATA) >

<!-- Factura -->
<!ELEMENT factura (descuento, productos_facturados)>
<!ATTLIST factura 
    codigo CDATA #REQUIRED
    fecha CDATA #REQUIRED
    hora CDATA #REQUIRED
    dni_cliente CDATA #REQUIRED >
<!ELEMENT descuento (#PCDATA) >

<!-- Productos Facturados -->
<!ELEMENT productos_facturados (producto_facturado*) >

<!-- Producto Facturado -->
<!ELEMENT producto_facturado (unidades, descripcion, precio, iva) >
<!ATTLIST producto_facturado id CDATA #REQUIRED >
<!ELEMENT unidades (#PCDATA) >

=== maximka76667/xml-facturas/facturas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE facturas SYSTEM "facturas.dtd">

<facturas>
    <provincias>
        <provincia id="00">
            <nombre> </nombre>
        </provincia>
    </provincias>
    <poblaciones>
        <poblacion id_poblacion="LLL" id_provincia="00">
            <nombre> </nombre>
        </poblacion>
    </poblaciones>
    <clientes>
        <cliente dni="00000000L">
            <nombre> </nombre>
            <apellidos> </apellidos>
            <direccion>
                <codigo_poblacion>LLL</codigo_poblacion>
                <calle> </calle>
                <numero> </numero>
                <cp>00000</cp>
            </direccion>
        </cliente>
    </clientes>
    <productos>
        <!--  Datos Actuales  -->
        <producto id="Referencia1">
            <descripcion>Producto 1</descripcion>
            <precio>000000.000</precio>
            <iva>00</iva>
            <stock>00</stock>
        </producto>
        <producto id="Referencia2">
            <descripcion>Producto 2</descripcion>
            <precio>000000.000</precio>
            <iva>00</iva>
            <stock>00</stock>
        </producto>
    </productos>
    <factura codigo="X" fecha="dd/mm/aaaa" hora="hh:mm:ss" dni_cliente="00000000L">
        <descuento>00</descuento>
        <productos_facturados>
            <producto_facturado id="Referencia1">
                <unidades>000</unidades>
                <descripcion>Producto 1</descripcion>
                <!--  Estos datos podrÃ­an varian entre facturas  -->
                <precio>000000.000</precio>
                <iva>00</iva>
            </producto_facturado>
        </productos_facturados>
    </factura>
</facturas>
